version: '3.9'

networks:
  backend:
    name: network-back

services:
  database:
    container_name: mysql-cont
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bob
      MYSQL_DATABASE: testdb
    networks:
      - backend
    volumes:
      - D:\formation\docker\ynov\volumes\data:/var/lib/mysql
  phpmyadmin:
    container_name: admin-cont
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: bob
      PMA_HOST: database
    networks:
      - backend
    depends_on:
      - database
