version: '3.9'

networks:
  backend:
    name: network-back
  front:
    name: network-front

services:
  database:
    container_name: mysql-cont
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bob
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PWD}
    networks:
      - backend
      - front
    volumes:
      - D:\formation\docker\ynov\volumes\data:/var/lib/mysql
  phpmyadmin:
    container_name: admin-cont
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: bob
      PMA_HOST: database
    networks:
      - backend
    depends_on:
      - database
  wordpress:
    container_name: wp-cont
    image: wordpress:latest
    depends_on:
      - database
    networks:
      - front
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DB_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PWD}
      WORDPRESS_DB_NAME: ${DB_NAME}
