#BASE : 
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
LABEL name=web
WORKDIR /app

EXPOSE 80
EXPOSE 443

#BUILD : 
FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build

WORKDIR /src

COPY ./Web/ ./Web/
COPY ./Foundation/Http ./Foundation/Http/

RUN dotnet restore Web/Web.csproj 
RUN dotnet build Web/Web.csproj -c Release -o /app/build

#PUBLISH :
FROM build AS publish
RUN dotnet publish Web/Web.csproj -c Release -o /app/publish

#FINAL : 
FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish/ .

ENTRYPOINT [ "dotnet", "/app/Web.dll" ]