#BASE : 
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
LABEL name=web
WORKDIR /app

EXPOSE 80
EXPOSE 443

#BUILD : 
FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build

WORKDIR /src

COPY /Web/Web.csproj /src/Web/
COPY /Foundation/Http /src/Foundation/Http/

RUN dotnet restore /src/Web/Web.csproj.csproj 
RUN dotnet build /src/Web/Web.csproj.csproj -c Release -o /app/build

#PUBLISH :
FROM build AS publish
RUN dotnet /src/Web/Web.csproj.csproj -c Release -o /app/publish

#FINAL : 
FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish/ .

ENTRYPOINT [ "dotnet", "/app/Web.dll" ]