#BASE : 
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base

WORKDIR /app

EXPOSE 80
EXPOSE 443

#BUILD : 
FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build

WORKDIR /src

COPY D:\YNOV_M2\Docker\Project\appscore\Web\Web.csproj /src/Web/
COPY D:\YNOV_M2\Docker\Project\appscore\Foundation\Http /src/Foundation/Http/

RUN dotnet restore /src/Web/Web.csproj.csproj 
RUN dotnet build /src/Web/Web.csproj.csproj -c Release -o /app/build

#PUBLISH :
FROM build AS publish
RUN dotnet /src/Web/Web.csproj.csproj -c Release -o /app/publish

#FINAL : 
FROM base AS final

WORKDIR /app

COPY /app /app/publish/Web.csproj.dll

RUN dotnet Web.dll