FROM mcr.microsoft.com/mssql/server:2017-latest AS database

LABEL author="pierrelebris"
LABEL name="sql-server"

COPY /Database/SqlCmdScript.sql SqlCmdScript.sql
COPY /Database/entrypoint.sh entrypoint.sh
COPY /Database/SqlCmdStartup.sh SqlCmdStartup.sh

ENV ACCEPT_EULA=Y
ENV MYSQL_SA_PASSWORD=Pass@word

CMD /bin/bash ./entrypoint.sh

VOLUME sqlserver

EXPOSE 1433